### PR TITLE
Add PHP 8.x compatibilty (tested on PHP 8.2). Document the installation of shims to run old PHP functions.

### PR DESCRIPTION
**Pull request by Poikilos**

### CODE REVIEW

**Comment by bjorn** [comment]
This is really an amazing feat! There's so much involved in this update, it's a little baffling how you've actually pulled it off. Thank you!

Now, there are still some remaining issues:

* I've changed the server to use a git checkout, to make it easier to keep it up to date. However, now the deletion of `forums/install` is a local change. Do you have any suggestions for dealing with this?

* It would be nice if the database user wasn't edited into a checked-in file. Maybe `forums/config.php` should be moved to `forums/config.php.sample`?

* I could not get the `auto_prepend_file` setting to work, so instead I've included the shims in `forums/common.php`. This is of course another annoying local change.

* I had to comment out a lot more duplicate defines. Actually I don't know what the code expected before, but I've basically commented out all RPGDX-specific defines from `forums/includes/constants.php` (except `READS_TABLE`), since they were also being defined at `includes/constants.php`. It's a local change until we figure out the proper fix.

* Apparently I am accessing rpgdx.net over IPv6 and the `encode_ip` function choked on it. Given that the result of that function is even stored in the DB in a `char(8)`, I hacked it to just return `FFFFFFFF` when the IP address isn't IPv4. This of course breaks IP bans and possibly other IP-based checks.

And then there are some errors I haven't gotten around to look into yet:

* https://rpgdx.net/showgame.php?project_id=211

  `Fatal error: Uncaught TypeError: sizeof(): Argument #1 ($value) must be of type Countable|array, null given in /home/public/showgame.php:203 Stack trace: #0 {main} thrown in /home/public/showgame.php on line 203`

* https://rpgdx.net/profile.php?user_id=9

   I can't find my own posts (also I can't login), likely due to encoding issues in my name (#2).

* https://rpgdx.net/forums/viewtopic.php?t=2831

   None of the forum posts are showing their contents. :-(

But again, thank you so much for all the updates! It would be great if you can help resolve the remaining issues as well, but I'll also see if I can resolve some of these eventually.

**Comment by bjorn** [comment]
I've addressed the `sizeof()` error in 661857c21cf4e4bdaea72141bac71d1c84bc7be5 and created #10 about the empty forum posts.

**Comment by Poikilos** [comment]
> * I've changed the server to use a git checkout, to make it easier to keep it up to date. However, now the deletion of `forums/install` is a local change. Do you have any suggestions for dealing with this?

See https://github.com/bjorn/rpgdx/issues/11#issuecomment-2125937029

**Comment by Poikilos** [comment]
> * It would be nice if the database user wasn't edited into a checked-in file. Maybe `forums/config.php` should be moved to `forums/config.php.sample`?

Yes!

Then add config.php to .gitignore

**Comment by Poikilos** [comment]
You are very welcome. I have fond memories of playing the RPGs on the site.

**Pull request merged**
